### PR TITLE
fix(image): disable source repos

### PR DESCRIPTION
**Pull request by helgi**
Goes from needing to pull 22 to 12 repos

### CODE REVIEW

**Comment by krancour** [comment]
This LGTM, but I also think we should maybe do a trial rebuild of ome of the other images that are derived from this to understand how much of a difference it makes. What do you think?

**Comment by helgi** [comment]
https://github.com/deis/controller/pull/764 has the same change (plus others) for that very reason. Obviously it may not be enough but gives us an idea

**Comment by krancour** [comment]
This seems to make a negligible difference in the size of this image itself. Having said that, I think this is a positive change in that other images that are `FROM` this will pick up this optimization and hopefully it makes a greater difference in some of those cases. LGTM

**Comment by helgi** [comment]
This won't change the size of the image, it change the speed of which you can make the image by a handful of seconds ;) Matters more if you are on a slower connection :)

**Pull request merged**
